# Generated by Django 6.0.6 on 2026-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_student_address_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
