# Generated by Django 6.0.6 on 2026-06-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_student_dob_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
