# Generated by Django 6.0.6 on 2026-06-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
