# Generated by Django 6.0.6 on 2026-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_student_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
