# Generated by Django 6.0.6 on 2026-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_student_application_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
