# Generated by Django 6.0.6 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
