# Generated by Django 6.0.6 on 2026-06-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_student_marksheet_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
