# Generated by Django 6.0.6 on 2026-06-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
